In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import model_selection 
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
import xgboost 

#change the location first
Ref_case = pd.read_csv('E:\Thesis\Ref_case_351.csv')

In [4]:
array= np.array(Ref_case)
X = array[:, :2]

In [6]:
X.shape

(2496, 2)

In [7]:
Y = array[:, 2:3]
Y = Y.reshape(-1)

In [9]:
Y.shape

(2496,)

In [10]:
print(Ref_case.groupby('Class').size())

Class
Core          416
Core_ok       416
IBW           416
IBW_ok        416
Winding       416
Winding_ok    416
dtype: int64


In [51]:
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

#label encoding
label_encoder = LabelEncoder()
label_encoder = label_encoder.fit(Y)
label_encoded_y = label_encoder.transform(Y)
print(label_encoded_y)


[1 1 1 ... 4 4 4]


In [52]:

np.unique(label_encoded_y)

array([0, 1, 2, 3, 4, 5])

In [323]:
test_size= .20
seed= 1

X_train, X_test, y_train, y_test = train_test_split(X, label_encoded_y, test_size=test_size, random_state=seed)

In [324]:
# fit model 
model = xgboost.XGBClassifier(learning_rate =0.00001,
 n_estimators=21,
 max_depth=5,
 min_child_weight=16,
 gamma=0.3,
 subsample=0.8,
 colsample_bytree=0.4,
 objective= 'multi:softmax',
 nthread=4,
 scale_pos_weight=0)
model.fit(X_train, y_train)
print(model)
# make predictions for test data
y_pred = model.predict(X_test)
predictions = [round(value) for value in y_pred]
# evaluate predictions
accuracy = accuracy_score(y_test, predictions)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=0.4, gamma=0.3, learning_rate=1e-05,
       max_delta_step=0, max_depth=5, min_child_weight=16, missing=None,
       n_estimators=21, n_jobs=1, nthread=4, objective='multi:softprob',
       random_state=0, reg_alpha=0, reg_lambda=1, scale_pos_weight=0,
       seed=None, silent=True, subsample=0.8)
Accuracy: 50.40%


In [325]:
#predictions= clf.predict(X_test)
print(accuracy_score(y_test, predictions))
print(confusion_matrix(y_test, predictions))
print(classification_report(y_test, predictions))

0.504
[[16 72  0  0  0  0]
 [10 59  0  0  0  0]
 [ 0  0  1 88  0  0]
 [ 0  0  2 96  0  0]
 [ 0  0  0  0 45 31]
 [ 0  0  0  0 45 35]]
              precision    recall  f1-score   support

           0       0.62      0.18      0.28        88
           1       0.45      0.86      0.59        69
           2       0.33      0.01      0.02        89
           3       0.52      0.98      0.68        98
           4       0.50      0.59      0.54        76
           5       0.53      0.44      0.48        80

   micro avg       0.50      0.50      0.50       500
   macro avg       0.49      0.51      0.43       500
weighted avg       0.49      0.50      0.43       500

