In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import model_selection 
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report
import xgboost 

Ref_case = pd.read_csv('E:\Thesis\Ref_case 35.csv')


array= np.array(Ref_case)


X = array[:, :2]

In [2]:
Y = array[:, 2:3]
Y = Y.reshape(-1)

In [3]:
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

label_encoder = LabelEncoder()
label_encoder = label_encoder.fit(Y)
label_encoded_y = label_encoder.transform(Y)
print(label_encoded_y)

[0 0 0 ... 2 2 2]


In [4]:
np.unique(label_encoded_y)

array([0, 1, 2])

In [6]:
print(Ref_case.groupby('Class').size())

Class
Core       500
Winding    500
ok         500
dtype: int64


import random

random.shuffle(X)
random.shuffle(y)

In [9]:
test_size= .20
seed= 6

X_train, X_test, y_train, y_test = train_test_split(X, label_encoded_y, test_size=test_size, random_state=seed)

In [10]:
# fit model no training data
model = xgboost.XGBClassifier()
model.fit(X_train, y_train)
print(model)
# make predictions for test data
y_pred = model.predict(X_test)
predictions = [round(value) for value in y_pred]
# evaluate predictions
accuracy = accuracy_score(y_test, predictions)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
       n_jobs=1, nthread=None, objective='multi:softprob', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1)
Accuracy: 60.33%


In [13]:
print(accuracy_score(y_test, predictions)*100,'%')
print(confusion_matrix(y_test, predictions))
print(classification_report(y_test, predictions))

60.333333333333336 %
[[ 61   0  33]
 [  0 107   0]
 [ 86   0  13]]
              precision    recall  f1-score   support

           0       0.41      0.65      0.51        94
           1       1.00      1.00      1.00       107
           2       0.28      0.13      0.18        99

   micro avg       0.60      0.60      0.60       300
   macro avg       0.57      0.59      0.56       300
weighted avg       0.58      0.60      0.57       300



In [119]:
X_test

array([[26.178, -0.036988171],
       [942.7130000000001, -2.015841335],
       [12002.271, -18.81932931],
       [636565.466, -13.92322894],
       [121.806, -0.083127642],
       [5657.206999999999, -12.78112199],
       [521643.619, -21.53377526],
       [1533.729, -3.961336479],
       [877312.917, -16.28141248],
       [21098.88, -23.31246625],
       [255.58, -0.227933102],
       [86.447, -0.057480252],
       [20.074, -0.034805814],
       [15825.575, -21.04804644],
       [441892.11600000004, -25.74566459],
       [906913.8890000001, -14.41655847],
       [145.388, -0.10083404900000001],
       [2696.153, -7.299059185],
       [6045.401, -13.30652311],
       [5009.101, -11.83134887],
       [429.84, -0.551048431],
       [14168.408000000001, -20.15878955],
       [166946.786, -38.786619200000004],
       [472214.492, -25.79716109],
       [1830.67, -4.899800957],
       [10985.825, -18.1061987],
       [3011.5009999999997, -8.056566638],
       [27.666, -0.037063592],
       

In [115]:
predictions

[0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 2,
 1,
 1,
 1,
 0,
 0,
 1,
 2,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 2,
 1,
 1,
 2,
 0,
 0,
 0,
 1,
 2,
 1,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 2,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 2,
 1,
 2,
 1,
 0,
 0,
 2,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 2,
 1,
 1,
 0,
 0,
 2,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 2,
 1,
 1,
 2,
 0,
 1,
 0,
 2,
 0,
 0,
 1,
 2,
 2,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 2,
 1,
 0,
 1,
 2,
 0,
 1,
 1,
 0,
 1,
 2,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 1,
 2,
 2,
 2,
 2,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 2,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 1,
 2,
 1,
 0,
 2,
 0,
 2,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 2,
 0,
 0,
 0,
 2,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 2,
 0,
 0,
 1,
 0,
 1,
 1,
 2,
 0,
 2,
 0,
 0,
 1,
 1,
 0,
